version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - todo-network

  todo-app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
